version: '3.5'

services:

 nginx:
  image: nginx
  build: requirements/nginx/
  container_name: nginx
  env_file: .env
  ports:
   - "443:443"
  volumes:
   - wpdata:/var/www/html
  networks:
   - inception_network
  restart: always
  depends_on:
   - wordpress

 wordpress:
  image: wordpress
  build: requirements/wordpress/
  container_name: wordpress
  env_file: .env
  networks:
   - inception_network
  volumes:
   - wpdata:/var/www/html
  restart: always
  depends_on:
   - mariadb

 mariadb:
  image: mariadb
  build: requirements/mariadb/
  container_name: mariadb
  env_file: .env
  networks:
   - inception_network
  volumes:
   - dbdata:/var/lib/mysql
  restart: always
  
 adminer:
  image: adminer
  build: requirements/adminer
  container_name: adminer
  env_file: .env
  networks:
   - inception_network
  restart: always
  depends_on:
   - wordpress

volumes:
 wpdata:
  name: wpdata
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/bchelste/data/wpdata'

 dbdata:
  name: dbdata
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/bchelste/data/dbdata'

networks:
 inception_network:
  name: inception_network
  driver: bridge
